apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: demo-voting-app
spec:
#  Selector is going to use same labels we used in the pod definition file. This will link the service to the pod.
  selector:
    name: redis-pod
    app: demo-voting-app
  ports:
  - port: 6379
    targetPort: 6379
