apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: demo-voting-app
spec:
#  Selector is going to use same labels we used in the pod definition file. This will link the service to the pod.
  selector:
    name: result-app-pod
    app: demo-voting-app
  # This exposes it eternally. 
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30005
