apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: demo-voting-app
spec: 
#  Selector is going to use same labels we used in the pod definition file. This will link the service to the pod.
  selector:
    name: voting-app-pod
    app: demo-voting-app
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30004
